# Senin
[[senin]]
jam = '07:00'
file = 'upacara_kurang_5_menit.mp3'
[[senin]]
jam = '08:20'
file = '1.mp3'
[[senin]]
jam = '09:00'
file = '2.mp3'
[[senin]]
jam = '09:40'
file = 'istirahat.mp3'
[[senin]]
jam = '09:55'
file = 'istirahat_kurang_5_menit.mp3'
[[senin]]
jam = '10:00'
file = '3.mp3'
[[senin]]
jam = '10:40'
file = '4.mp3'
[[senin]]
jam = '11:20'
file = '5.mp3'
[[senin]]
jam = '12:00'
file = 'istirahat.mp3'
[[senin]]
jam = '13:10'
file = 'istirahat_kurang_5_menit.mp3'
[[senin]]
jam = '13:15'
file = '6.mp3'
[[senin]]
jam = '13:55'
file = '7.mp3'
[[senin]]
jam = '14:35'
file = 'istirahat.mp3'
[[senin]]
jam = '15:25'
file = 'istirahat_kurang_5_menit.mp3'
[[senin]]
jam = '15:30'
file = '8.mp3'
[[senin]]
jam = '16:30'
file = 'akhir_pelajaran.mp3'

# Selasa
[[selasa]]
jam = '07:00'
file = '1.mp3'
[[selasa]]
jam = '07:40'
file = '2.mp3'
[[selasa]]
jam = '08:20'
file = '3.mp3'
[[selasa]]
jam = '09:00'
file = '4.mp3'
[[selasa]]
jam = '09:40'
file = 'istirahat.mp3'
[[selasa]]
jam = '09:55'
file = 'istirahat_kurang_5_menit.mp3'
[[selasa]]
jam = '10:00'
file = '5.mp3'
[[selasa]]
jam = '10:40'
file = '6.mp3'
[[selasa]]
jam = '11:20'
file = '7.mp3'
[[selasa]]
jam = '12:00'
file = 'istirahat.mp3'
[[selasa]]
jam = '13:10'
file = 'istirahat_kurang_5_menit.mp3'
[[selasa]]
jam = '13:15'
file = '8.mp3'
[[selasa]]
jam = '13:55'
file = '9.mp3'
[[selasa]]
jam = '14:35'
file = 'istirahat.mp3'
[[selasa]]
jam = '15:25'
file = 'istirahat_kurang_5_menit.mp3'
[[selasa]]
jam = '15:30'
file = '10.mp3'
[[selasa]]
jam = '16:30'
file = 'akhir_pelajaran.mp3'
# Rabu, Kamis, Sabtu ikut Hari Selasa!


# Jum'at (apostrop dihilangkan)
[[jumat]]
jam = '07:00'
file = '1.mp3'
[[jumat]]
jam = '07:40'
file = '2.mp3'
[[jumat]]
jam = '08:20'
file = '3.mp3'
[[jumat]]
jam = '09:00'
file = '4.mp3'
[[jumat]]
jam = '09:40'
file = 'istirahat.mp3'
[[jumat]]
jam = '09:55'
file = 'istirahat_kurang_5_menit.mp3'
[[jumat]]
jam = '10:00'
file = '5.mp3'
[[jumat]]
jam = '10:40'
file = '6.mp3'
[[jumat]]
jam = '11:20'
file = 'istirahat.mp3'
[[jumat]]
jam = '13:10'
file = 'istirahat_kurang_5_menit.mp3'
[[jumat]]
jam = '13:15'
file = 'kerohanian_dimulai.mp3'
[[jumat]]
jam = '14:35'
file = 'istirahat.mp3'
[[jumat]]
jam = '15:25'
file = 'istirahat_kurang_5_menit.mp3'
[[jumat]]
jam = '15:30'
file = '7.mp3'
[[jumat]]
jam = '16:30'
file = 'akhir_pelajaran.mp3'