# Path absolut folder MP3; kosong memakai assets bawaan.
sound_dir = ""

# Senin
senin = [
    # jam 1
    { jam = "07:15", file = "masuk_ruang_ujian.mp3" },
    { jam = "07:30", file = "mengerjakan_ujian.mp3" },
    { jam = "08:55", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "09:00", file = "waktu_ujian_telah_habis.mp3" },
    # jam 2
    { jam = "09:30", file = "masuk_ruang_ujian.mp3" },
    { jam = "09:45", file = "mengerjakan_ujian.mp3" },
    { jam = "11:10", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "11:15", file = "waktu_ujian_telah_habis.mp3" },
]

# Selasa
selasa = [
    { jam = "07:15", file = "masuk_ruang_ujian.mp3" },
    { jam = "07:30", file = "mengerjakan_ujian.mp3" },
    { jam = "08:55", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "09:00", file = "waktu_ujian_telah_habis.mp3" },
    # jam 2
    { jam = "09:30", file = "masuk_ruang_ujian.mp3" },
    { jam = "09:45", file = "mengerjakan_ujian.mp3" },
    { jam = "11:10", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "11:15", file = "waktu_ujian_telah_habis.mp3" },
]

# Rabu
rabu = [
    { jam = "07:15", file = "masuk_ruang_ujian.mp3" },
    { jam = "07:30", file = "mengerjakan_ujian.mp3" },
    { jam = "08:55", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "09:00", file = "waktu_ujian_telah_habis.mp3" },
    # jam 2
    { jam = "09:30", file = "masuk_ruang_ujian.mp3" },
    { jam = "09:45", file = "mengerjakan_ujian.mp3" },
    { jam = "11:10", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "11:15", file = "waktu_ujian_telah_habis.mp3" },
]

# Kamis
kamis = [
    { jam = "07:15", file = "masuk_ruang_ujian.mp3" },
    { jam = "07:30", file = "mengerjakan_ujian.mp3" },
    { jam = "08:55", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "09:00", file = "waktu_ujian_telah_habis.mp3" },
    # jam 2
    { jam = "09:30", file = "masuk_ruang_ujian.mp3" },
    { jam = "09:45", file = "mengerjakan_ujian.mp3" },
    { jam = "11:10", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "11:15", file = "waktu_ujian_telah_habis.mp3" },
]

# Jum'at (apostrop dihilangkan)
jumat = [
    { jam = "07:15", file = "masuk_ruang_ujian.mp3" },
    { jam = "07:30", file = "mengerjakan_ujian.mp3" },
    { jam = "08:55", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "09:00", file = "waktu_ujian_telah_habis.mp3" },
    # jam 2
    { jam = "09:30", file = "masuk_ruang_ujian.mp3" },
    { jam = "09:45", file = "mengerjakan_ujian.mp3" },
    { jam = "11:10", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "11:15", file = "waktu_ujian_telah_habis.mp3" },
]

# Sabtu
sabtu = [
    { jam = "07:15", file = "masuk_ruang_ujian.mp3" },
    { jam = "07:30", file = "mengerjakan_ujian.mp3" },
    { jam = "08:55", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "09:00", file = "waktu_ujian_telah_habis.mp3" },
    # jam 2
    { jam = "09:30", file = "masuk_ruang_ujian.mp3" },
    { jam = "09:45", file = "mengerjakan_ujian.mp3" },
    { jam = "11:10", file = "waktu_ujian_kurang_5_menit.mp3" },
    { jam = "11:15", file = "waktu_ujian_telah_habis.mp3" },
]
